title: Florian Latzel
description: Curriculum Vitae

theme: jekyll-theme-primer
baseurl: /cv

# url: "https://florian.latzel.io" 

# jekyll-seo-tag
lang: "de"
social:
  name: Florian Latzel

exclude:
  - vendor      
  - Gemfile
  - Gemfile.lock  
  - deploy.conf

git_repo: "https://github.com/fl3a/cv"
repository: "fl3a/cv"

