title: Florian Latzel
description: Curriculum Vitae

url: "https://florian.latzel.io" 
baseurl: /cv/

theme: jekyll-theme-primer

# jekyll-seo-tag
lang: "de"
social:
  name: Florian Latzel

exclude:
  - vendor      
  - Gemfile
  - Gemfile.lock  
  - deploy.conf

git_repo: "https://github.com/fl3a/cv"
repository: "fl3a/cv"

